name: Telegram Kino Bot 24/7

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:
  schedule:
    # Har 3 soatda avtomatik yangilanib, uzluksiz 24/7 ishlashini ta'minlaydi
    - cron: '0 */3 * * *'

permissions:
  contents: write
  actions: write

jobs:
  run-bot:
    runs-on: ubuntu-latest
    timeout-minutes: 350
    steps:
      - name: Repositoriyani yuklab olish
        uses: actions/checkout@v4

      - name: Python 3.11 ni sozlash
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Kerakli kutubxonalarni o'rnatish
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Botni ishga tushirish (24/7)
        env:
          BOT_TOKEN: "8970096817:AAHSNn7uriH_mMCeWjgvvLoh1sYBV39SSAQ"
          ADMINS: "7747943559"
          REQUIRED_CHANNEL: ""
          CHANNEL_URL: ""
          INSTAGRAM_URL: "https://instagram.com/asilbek_ravshanov04"
          INSTAGRAM_NAME: "asilbek_ravshanov04"
        run: |
          echo "=========================================="
          echo "🤖 Bugunkinolar_bot 24/7 serverda ishlamoqda..."
          echo "=========================================="
          python bot.py
